name: feedbacks
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.19.0
  image_picker: ^1.1.0        # Para selecionar imagens e vídeos
  file_picker: ^8.0.0         # Para selecionar qualquer tipo de arquivo
  open_file: ^3.3.0           # Para abrir arquivos baixados
  path_provider: ^2.1.0       # Para acessar diretórios do dispositivo
  permission_handler: ^11.0.0 # Para pedir permissões (Android/iOS)
  socket_io_client: ^2.0.3+1  # WebSocket para chat em tempo real

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/